#!/bin/bash
#PBS -k o
#PBS -M bkrosenz@indiana.edu
#PBS -l vmem=64gb,nodes=1:ppn=12,walltime=4:0:0 
#PBS -m abe
#PBS -N dbroot
#PBS -d /N/dc2/projects/bkrosenz/deep_ils/pbs

N=12

source ~/.bash_profile;
module load anaconda gsl gnu-parallel

source activate bio3.6

OUTDIR=/N/dc2/projects/bkrosenz/deep_ils/sims/seqgen-aa-theta0.01
WORKING_DIR=/N/dc2/projects/bkrosenz/deep_ils/code/pylib

### concatenate all the leftover raxml files

# cd $OUTDIR;
# find raxml -name 'RAxML_bestTree.*.raxml' |perl -pe 's/_[a-z]+_PROTCAT(WAG|LG).raxml/ PROTCAT$1/'|sort|uniq > raxml.txt

# concatenate(){
#     size=$(du -k "$3" | cut -f 1);
#     if [ $size -le 1 ];
#     then  cat ${1}_*_${2}.raxml > $3;
# 	  rm ${1}_*_${2}.raxml;
#     fi;
# }
# export -f concatenate;

# parallel -j$N --colsep ' '  concatenate {1} {2} tmp/{1}_{2}.raxml.trees :::: raxml.txt
# mv tmp/raxml/*trees inferred_trees/
# rename RAxML_bestTree.t_ t_ inferred_trees/* 

cd $WORKING_DIR;

pwd;

bash rooted.sh $OUTDIR $N;
echo finished rooting trees...;
qsub ../../pbs/updatedb.pbs
