#!/bin/bash
#PBS -k o
#PBS -M bkrosenz@indiana.edu
#PBS -l vmem=250gb,nodes=1:ppn=24,walltime=8:0:0
#PBS -m abe
#PBS -N calc-top
#PBS -d /N/dc2/projects/bkrosenz/deep_ils/pbs

source ~/.bash_profile;
M=240e9
N=24

module load gsl gnu-parallel;
WORKING_DIR=/N/dc2/projects/bkrosenz/deep_ils/sims/simphy/SimPhy38;

source activate bio3.6;
cd /N/dc2/projects/bkrosenz/deep_ils/code/simulate
pwd;

python simphy2arrow2.py -p $N -m $M --dirlist /N/dc2/projects/bkrosenz/deep_ils/sims/simphy/simdirs.aa.txt
