#!/bin/bash
#PBS -k o
#PBS -M bkrosenz@indiana.edu
#PBS -l vmem=76gb,nodes=1:ppn=8,walltime=16:0:0
#PBS -m abe
#PBS -N calc-top
#PBS -d /N/dc2/projects/bkrosenz/deep_ils/pbs

source ~/.bash_profile;
M=74e9
N=8

module load gsl gnu-parallel;
WORKING_DIR=/N/dc2/projects/bkrosenz/deep_ils/sims/simphy/SimPhy38;

source activate bio3.6;
cd /N/dc2/projects/bkrosenz/deep_ils/code/simulate
pwd;

python simphy2arrow2.py -p $N -m $M
