#!/bin/bash
#PBS -k o
#PBS -M bkrosenz@indiana.edu
#PBS -l vmem=96gb,nodes=1:ppn=8,walltime=23:0:0
#PBS -m abe
#PBS -N top1.a
#PBS -d /N/dc2/projects/bkrosenz/deep_ils/pbs

N=10

source ~/.bash_profile;
source activate bio
module load gsl gnu-parallel

WORKING_DIR=/N/dc2/projects/bkrosenz/deep_ils

cd $WORKING_DIR;
pwd;

############## WARNING!! WILL DELETE OLD STUFF ###
#mkdir top1  top2 top1/inferred_trees top1/raxml top1/seqs top1/trees  top2/inferred_trees top2/raxml top2/seqs top2/trees
# rm sims/top1/trees/* sims/top1/raxml/* sims/top1/seqs/* || {echo nothing in folders trees/ raxml/ seqs/}
# rm sims/top2/trees/* sims/top2/raxml/* sims/top2/seqs/* || {echo nothing in folders trees/ raxml/ seqs/}


#### arguments: <T_a> <Tb-T_a> <T_c-T_b> <data_dir> <raxml_binary_name> <suffix>                                                                                         ### where T_a = T(a,b), T_b = T((a,b),c), T_c = T(((a,b),c),o)

source ~/.bash_profile

scale=0.01 # theta for seqgen
outdir=/N/dc2/projects/bkrosenz/deep_ils/sims/seqgen-aa-1000bp-theta$scale

mkdir $outdir $outdir/trees $outdir/seqs $outdir/raxml $outdir/inferred_trees $outdir/empty_dir
# also JTT

echo started at `date`
parallel -j $N ./code/simulate/simulate.top1.AA.sh {} ::: `seq 60 10 250` ::: 0.01 `seq 0.02 0.02 0.2` 0.25 `seq 0.5 0.5 15` ::: 20 ::: $outdir ::: raxmlHPC ::: $scale
echo finished at `date`

qsub updatedb.pbs
