#!/bin/bash
#PBS -k o
#PBS -M bkrosenz@indiana.edu
#PBS -l vmem=64gb,nodes=1:ppn=16,walltime=12:0:0
#PBS -m abe
#PBS -N top1.a
#PBS -d /N/dc2/projects/bkrosenz/deep_ils/pbs

N=4

source ~/.bash_profile;
source activate bio3.6;

WORKING_DIR=/N/dc2/projects/bkrosenz/deep_ils/code;
cd $WORKING_DIR;
pwd;

# short run for testing
python simulate_master.p3.2.py -s WAG BLOSUM -m PROTCATWAGF  PROTCATBLOSUM62F \
       --ebl `seq 20 20 60` \
       --ibl  .01 .05 1 2 5 \
       --tout  20 \
       --raxml raxmlHPC -o ../databases/test_db.sql --loci 100 --procs $N

# python simulate_master.p3.2.py -s WAG BLOSUM -m PROTCATWAGF  PROTCATBLOSUM62F \
#        --ebl `seq 20 20 100` \
#        --ibl  `seq .01 .01 .1` `seq .2 .2 10` \
#        --tout  20 \
#        --raxml raxmlHPC -o ../databases/test_db.sql --loci 10000 --procs $N


echo finished at `date`
