#!/bin/bash
#PBS -k o
#PBS -M bkrosenz@indiana.edu
#PBS -l vmem=128gb,nodes=1:ppn=12,walltime=23:0:0
#PBS -m abe
#PBS -N top1.70.a
#PBS -d /N/project/phyloML/deep_ils/pbs

N=16

source ~/.bash_profile;
source activate py38 
module load gsl gnu-parallel

WORKING_DIR=/N/project/phyloML/deep_ils

cd $WORKING_DIR;
pwd;

#### arguments: <T_a> <Tb-T_a> <T_c-T_b> <data_dir> <raxml_binary_name> <suffix>                                                                                         ### where T_a = T(a,b), T_b = T((a,b),c), T_c = T(((a,b),c),o)

source ~/.bash_profile

scale=0.01 # theta for seqgen
outdir=/N/project/phyloML/deep_ils/sims/seqgen-aa-1000bp-theta$scale

mkdir $outdir $outdir/trees $outdir/inferred_trees $outdir/empty_dir
# also JTT

echo started at `date`
parallel -j $N ./code/simulate/simulate.top1.AA.sh {} ::: `seq 40 10 120` ::: 0.01 `seq 0.02 0.02 0.2` 0.25 `seq 0.5 0.5 15` ::: 20 ::: $outdir ::: raxmlHPC-AVX ::: $scale
echo finished at `date`

#qsub updatedb.pbs
