#!/bin/bash
#PBS -k o
#PBS -M bkrosenz@indiana.edu
#PBS -l vmem=32gb,nodes=1:ppn=4,walltime=17:0:0 
#PBS -m abe
#PBS -N dbupdate
#PBS -d /N/dc2/projects/bkrosenz/deep_ils/pbs

source ~/.bash_profile;
module load anaconda gsl gnu-parallel

source activate bio3.6

WORKING_DIR=/N/dc2/projects/bkrosenz/deep_ils/code/pylib

### concatenate all the leftover raxml files

# find raxml -name 'RAxML_bestTree.*.raxml' |perl -pe 's/_[a-z]+_PROTCAT(WAG|LG).raxml/ PROTCAT$1/'|sort|uniq > raxml.txt

# concatenate(){
#     size=$(du -k "$3" | cut -f 1);
#     if [ $size -le 1 ];
#     then  cat ${1}_*_${2}.raxml > $3;
# 	  rm ${1}_*_${2}.raxml;
#     fi;
# }
# export -f concatenate;

# parallel -j$N --colsep ' '  concatenate {1} {2} tmp/{1}_{2}.raxml.trees :::: raxml.txt
# mv tmp/raxml/*trees inferred_trees/
# rename RAxML_bestTree.t_ t_ inferred_trees/* 

cd $WORKING_DIR;

pwd;

#bash rooted.sh $N;
#echo finished rooting trees...;

pg_ctl -D /N/dc2/projects/bkrosenz/deep_ils/databases/pgsql/data -l logfile.updatedb start
#postgres -D /N/dc2/projects/bkrosenz/deep_ils/databases/pgsql/data >logfile.updatedb 2>&1 &

echo started db...;
bash update_sql_recomb.sh
echo updated postgresql db...
qsub ../../pbs/summarize.pbs
