#!/bin/bash
#PBS -k o
#PBS -M bkrosenz@indiana.edu
#PBS -l vmem=32gb,nodes=1:ppn=1,walltime=3:0:0
#PBS -m abe
#PBS -N calc-top
#PBS -d /N/dc2/projects/bkrosenz/deep_ils/pbs


M=16e9
N=2

module load anaconda/python3.6/4.3.1
source activate bio3.6;
cd /N/dc2/projects/bkrosenz/deep_ils/code/simulate
pwd;

python trees2arrow.py -p $N -m $M \
       --outdir /N/dc2/projects/bkrosenz/deep_ils/results \
       --indir /N/dc2/projects/bkrosenz/deep_ils/data/metazoa/whelan2017/metazoa_genes/trees \
       --outgroup Salpingoeca_rosetta

# /N/dc2/projects/bkrosenz/deep_ils/data/metazoa/whelan2017/species/choanoflagellata.whelan
